### ISSUE TITLE
Can not run configuration file

### ISSUE THREAD

**Issue by GintokiY** [breuner/elbencho#20]
When I run elbencho --configfile tools/example_configuration/randomWrite.elbencho /data, there is an error:
ERROR: Cannot open config file: tools/example_configuration/randomWrite.elbencho
How can I deal with this?

**Comment by GintokiY** [comment]
my path was wrong

**Comment by breuner** [comment]
Thanks for the hint, @GintokiY. Indeed the config file example path mentioned in the README.md was different from the actual directory name of the example file. I have now updated the directory name to be in line with the README.md.
