### ISSUE TITLE
Option to convert milliseconds to seconds, minutes or hours?

### ISSUE THREAD

**Issue by jasonmicron** [breuner/elbencho#34]
Hi Sven! Nice chatting with you in Slack a few weeks ago. Love the tool here, I have added it to my toolkit for certain.

I was curious if there would be any way to add a switch or option where when results are printed at the end if there could be a way to have elbencho show time in seconds or minutes (or maybe even hours). Currently, once the results are in a .csv I have to go in and divide the milliseconds by 1000 for seconds or 60000 for minutes and it is just an extra step.

Not the end of the world or anything, but I thought I'd ask. Thanks!

**Comment by breuner** [comment]
Hi Jason, nice to meet you here on github, too! Thanks for your suggestion. Sounds like a good idea. 
Just for clarification: 
You mentioned .csv, so I assume this is about the corresponding "time ms" column(s) in the .csv file that gets generated with the `--csvfile` option. Is this correct? 
If so, how exactly should this be changed to make your life easier? Should this new elbencho parameter (btw: please feel to also suggest a name for it) change the content of this column to the format `hours:mins:secs.millisecs` or to some other format?

**Comment by breuner** [comment]
Hi @jasonmicron  , I'm closing this due to no reply for several months. But of course please feel free to re-open if you have a new comment to add, e.g. with a suggestion for the ideal time format.
