### ISSUE TITLE
Lot of idle threads when running READ/WRITE on Lustre FS

### ISSUE THREAD

**Issue by grandsuri** [breuner/elbencho#37]
Hi,
We are trying to run elbencho command on LustreFS with 64 threads and the filesize and the blocksize being 1MB. We are seeing lot of threads idle even though the system has 256 cores and the system CPU usage shows 100% idle. I am wondering if there are tunable parameters in the elbencho to make all the threads active at a given time.

![image](https://user-images.githubusercontent.com/505886/221064737-d7e16b90-8e1c-4ed8-9ee4-ccff911470d4.png)

**Comment by grandsuri** [comment]
The command used is
`./elbencho -r --threads 64 --block 1M --size 1m --files 10 -n 64 --direct /mnt/lustrefs/htest7`

Eventually all the threads are pushing 640 files of 1MB each. But the concern is with the active threads at a given time which impacts the overall performance.

**Comment by breuner** [comment]
Hi @grandsuri, I'm closing this due to no reply for several months. Please feel free to re-open if you have news.
