### ISSUE TITLE
Question about --size

### ISSUE THREAD

**Issue by USTC-ERIC** [breuner/elbencho#38]
Hi, 
Thank you for sharing this useful tool. Recently, during my attempt to use it instead of fio for SSD performance analysis, I found that "elbencho -- size" cannot be set with a percentage like "fio -- size=100% ", or reporting "Unable to parse string for unit conversion: 100%". It seems that elbencho cannot recognize the capacity of an nvme device, or maybe I'm not familiar with this tool yet.

**Comment by breuner** [comment]
Hi @USTC-ERIC, 
thanks for the kind words.
Indeed, elbencho currently does not support `%` as a suffix for the `--size` parameter. You can use suffixes for GiB (e.g. `elbencho -r -t 16 -b 1m --size 100g /dev/nvme0n1` to only use the first 100GB of the NVMe device) or you can omit the size completely, in which case elbencho will use the full size of the device, e.g. like this:
```
$ sudo elbencho -r --rand --direct -t 64 -b 1m --timelimit 10 /dev/nvme0n1

NOTE: Auto-setting size to detected block dev size: 3840755982336

OPERATION RESULT TYPE        FIRST DONE  LAST DONE
========= ================   ==========  =========
READ      Elapsed ms       :      10000      10013
          IOPS             :       4617       4617
          Throughput MiB/s :       4617       4617
          Total MiB        :      46179      46239
---
Terminating due to phase time limit.
```

Is this good enough for what you need or do you think the `%` suffix is very important?

**Comment by breuner** [comment]
Hi @USTC-ERIC , I'm closing this due to no reply for several months. Please feel free to re-open if you have anything new to add.
