### ISSUE TITLE
support for S3 byte-range reads

### ISSUE THREAD

**Issue by mhanafi1970** [breuner/elbencho#48]
Is there any support for 'random read' byte-range reads on s3 objects?

Thanks,
Mahmoud

**Comment by breuner** [comment]
Hi Mahmoud,

yes, this works based on the block size (`-b`) being smaller than the object size (`-s).

For example, if you have the block size equal to the object size (`elbencho -r -b 100m -s 100m`) then elbencho will download the entire object in a single GET request. But if you set the block size smaller than the object size (`elbencho -r -b 1m -s 100m`)  then elbencho will do byte-range reads of the object in 1MB chunks. By default these will be sequential reads, but you can add `--rand` to make it random reads.

By the way: It's similarly for uploads (PUTs): If the block size for writes is equal to the object size then elbencho will use a single PUT request to upload the object. If the block size is smaller than the object size then elbencho will automatically use multi-part upload.

**Comment by mhanafi1970** [comment]
Is there a way to shift the reader like IOR -C

**Comment by breuner** [comment]
Hi Mahmoud,
there is currently no parameter for this. Assuming you use a hostsfile with one host per line, you could achieve this by simply rotating your hosts file between the tests, e.g. like this:

```
# original hostsfile:
user@host$ cat hosts.txt
node001
node002
node003

# read file lines into array and move first element to tail:
user@host$ MYHOSTS=($(cat /tmp/hosts.txt)); for i in ${MYHOSTS[@]:1}; do echo $i; done > hosts.txt; echo ${MYHOSTS[0]} >> hosts.txt

# this is what the file looks like after rotation:
user@host$ cat hosts.txt
node002
node003
node001
```

If that seems too inconvenient then it also shouldn't be complicated to add a parameter for this, just let me know.

**Comment by breuner** [comment]
Hi Mahmoud,

I've added a new option `--rotatehosts SOME_NUMBER` and pushed this to the master branch. With this, you can now shift the readers after a write phase like you mentioned above. Under the hood, it rotates the hosts list that you provide by the given SOME_NUMBER. You probably want to just use 1 for this (`elbencho --rotatehosts 1 --hosts ...`) to left-rotate the list by one position after each test phase, but you can also use a higher number if that ever makes sense.

I'm closing this issue now, but of course please feel free to re-open this issue or to open a new one if anything else comes up.
