### ISSUE TITLE
Continue on when encountering s3 errors

### ISSUE THREAD

**Issue by russki** [breuner/elbencho#52]
We're using elbencho to stress/load-test local s3 server. Elbencho quits as soon as it encounters a single error.

> 17:21:37.689 ERROR: Object download failed. Endpoint: xxxxx; Bucket: elbencho-job; Object: biggie/file40; Range: bytes=56699904-56700927; Exception: ; Message: No response body.; HTTP Error Code: 502

It would be great if there was an option to continue on with the test and just log/ignore the number of errors encountered

**Comment by breuner** [comment]
I can see your point. Would it work for you if I add an option like `elbencho --ioerrorfile /path/to/some/file.log` and when this option is given, elbencho will just log IO errors (like the one you used as an example) to that log file and keep running? 
The risk that I see here is that this file can get big if the server or gateway is failing a lot, but maybe that's an acceptable risk.

**Comment by russki** [comment]
yeah, that's a great solution. user could also potentially specify `/dev/null` if they didn't want to run out of disk space
