### ISSUE TITLE
Protect distributed mode (--service) with a secret

### ISSUE THREAD

**Issue by jbd** [breuner/elbencho#53]
Hello,

I wonder if it would be possible to protect a distributed run (--service) to be hijacked by providing a secret, a path to a file containing a secret or an accessible sentinel pathname from all hosts involved in the bench (that would leverage whatever filesystem permission is in place). Maybe I've missed something already implemented ? 

Right now, I'm quite nervous during the time window after I ran elbencho --service on a bunch of hosts ;)

Thank you for this great tool.

**Comment by breuner** [comment]
Certainly a good idea. I'll add an option for a file with a shared secret like you suggested.
(And thanks for the kind words :-) )

**Comment by breuner** [comment]
Hi @jbd, this feature is now included in the latest elbencho elbencho v3.0.9. 

It's based on a shared secret option, so you provide a file with the same text as `--svcpwfile /path/to/password.txt` parameter to the service instances on startup and when sending a command to the services via the master.

This will not help against a man in the middle attack where someone intercepts the network packages to steal the secret (addressing this would require at least a challenge/response protocol), but this should easily prevent any normal unauthorized user from hijacking your service instances in an evil way.

I'm marking this request as resolved, but of course please feel free to re-open if something isn't working for you or if there is any other question left.
