### ISSUE TITLE
Storage bench mark tests for HPC

### ISSUE THREAD

**Issue by ManikantaPulikonda99** [breuner/elbencho#64]

**Comment by breuner** [comment]
Hi @ManikantaPulikonda99, seems like the description text is missing or did you open this issue by accident?

**Comment by breuner** [comment]
Closing this issue because it seems like it was opened by accident. Please feel free to re-open if needed.

**Comment by ManikantaPulikonda99** [comment]
I might have opened by accident.
Please, close the ticket.
